# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41327f3319e49d31b928232249c4acb4217ded98ec7b1f666757444c52c46e7108f7205ce6cec33c396843674768f931cd5f442ef8c809d61e4a90127647c79b

test:
  secret_key_base: 9243fa6af3c26c8ebdf64c5a06e8f8a865548e9f9cc0425834b4c76cc7b90ddde17ce27ca9b8a3f1dfcb923e4806dbc40e98b97f4d83f3604f53a45228686099

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
